import os
import base64
import mimetypes
from dotenv import load_dotenv

load_dotenv(override=True, verbose=True)

MODEL_METRICS = {
    'BG': {'precision': 0.9615, 'recall': 1.0, 'f1-score': 0.9804},
    'D': {'precision': 0.8293, 'recall': 0.7391, 'f1-score': 0.7816},
    'N': {'precision': 0.9259, 'recall': 1.0, 'f1-score': 0.9615},
    'P': {'precision': 0.6429, 'recall': 0.2647, 'f1-score': 0.375},
    'S': {'precision': 0.6667, 'recall': 0.5714, 'f1-score': 0.6154},
    'V': {'precision': 0.6556, 'recall': 0.9516, 'f1-score': 0.7763}
}

def get_gemini_client():
    """
    Return a configured Gemini client instance using the API key from environment variables.
    """
    try:
        from google import genai
        
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY not found in environment variables")
        
        client = genai.Client(api_key=api_key)
        return client
    except ImportError:
        raise ImportError("google-genai library not installed. Run: pip install google-genai")

def describe_image_with_analysis(image_path: str, dados_analise: dict):
    """
    Generate a detailed technical description of the classified image using Gemini, incorporating the analysis data and model metrics.
    """
    try:
        client = get_gemini_client()
        
        with open(image_path, "rb") as f:
            image_data = f.read()
        
        predicted_class = dados_analise.get('predicted_class', 'Unknown')
        translated_class = dados_analise.get('translated_class', 'Unknown')
        confianca = dados_analise.get('predicted_percentage_confidence', 'N/A')
        probabilidades = dados_analise.get('complete_probabilities', {})
        
        prompt = f"""
        You are a Clinical Decision Support Artificial Intelligence (CDSS) system specialized in the initial screening and classification of skin lesions. Your goal is to generate a concise PRELIMINARY TECHNICAL REPORT and RISK REPORT, using strictly medical language, to be read and validated by a specialist physician.
        
        INPUT INFORMATION FOR THE CLASSIFICATION MODEL (VGG16 Fine-Tuned):
        1. PREDICTED CLASS: {predicted_class} ({translated_class}) - Confidence: {confianca}
        2. PROBABILITY VECTOR: {probabilidades}
        3. HISTORICAL MODEL METRICS FOR THE PREDICTED CLASS:
           - Precision: {MODEL_METRICS.get(predicted_class, {}).get('precision', 'N/A'):.4f}
           - Recall: {MODEL_METRICS.get(predicted_class, {}).get('recall', 'N/A'):.4f}
           - F1-Score: {MODEL_METRICS.get(predicted_class, {}).get('f1-score', 'N/A'):.4f}

        REQUIRED INFORMATION FOR THE ANSWER (Do not exceed 300 words):

        * Identify the primary classification and the model confidence.
        * Justify. Describe the visual characteristics of the image that corroborate the classification {predicted_class} ({translated_class}).
        * Perform a differential analysis. Comment on the 2-3 classes with the highest probability after the primary one, briefly explaining the similarities and differences.
        
        Format your response clearly and technically, using bullet points when appropriate, but never use titles. Only plain text and formatting such as bold, italics, lists, etc. No titles.

        Be formal and objective. NEVER USE TITLES OR SUBTITLES. NO H1, H2, H3, ETC.
        """

        from google.genai import types
        
        response = client.models.generate_content(
            model='gemini-2.5-flash-lite',
            contents=[
                prompt,
                types.Part.from_bytes(
                    data=image_data,
                    mime_type=mimetypes.guess_type(image_path)[0] or 'image/jpeg'
                )
            ]
        )
        
        return response.text.strip()
        
    except Exception as e:
        print(f"❌ Error generating image description: {e}")
        return f"""
        **PRELIMINARY TECHNICAL REPORT - CLASSIFIED IMAGE**

        **Primary Classification:** {dados_analise.get('predicted_class', 'N/A')} ({dados_analise.get('translated_class', 'N/A')})
        **Model Confidence:** {dados_analise.get('predicted_percentage_confidence', 'N/A')}
        **Historical F1-Score:** {dados_analise.get('metric_f1_predicted_class', 'N/A'):.4f}

        **Differential Analysis (Top 3):**
        {', '.join([f"{k}: {v}" for k, v in list(dados_analise.get('complete_probabilities', {}).items())[:3]])}

        **WARNING:** This is a preliminary report generated by AI and must be validated by direct clinical evaluation.

        For pressure ulcers (Class P), the model has a historical recall of only 0.2647.
        """