import os
import base64
import mimetypes
from dotenv import load_dotenv

load_dotenv(override=True, verbose=True)

METRICAS_MODELO = {
    'BG': {'precision': 0.9615, 'recall': 1.0, 'f1-score': 0.9804},
    'D': {'precision': 0.8293, 'recall': 0.7391, 'f1-score': 0.7816},
    'N': {'precision': 0.9259, 'recall': 1.0, 'f1-score': 0.9615},
    'P': {'precision': 0.6429, 'recall': 0.2647, 'f1-score': 0.375},
    'S': {'precision': 0.6667, 'recall': 0.5714, 'f1-score': 0.6154},
    'V': {'precision': 0.6556, 'recall': 0.9516, 'f1-score': 0.7763}
}

def get_gemini_client():
    """
    Retorna o cliente do Gemini usando google-genai
    """
    try:
        from google import genai
        
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            raise ValueError("GEMINI_API_KEY não encontrada")
        
        client = genai.Client(api_key=api_key)
        return client
    except ImportError:
        raise ImportError("Biblioteca google-genai não instalada")

def describe_image_with_analysis(image_path: str, dados_analise: dict):
    """
    Gera uma descrição técnica detalhada da imagem com base na análise do modelo
    """
    try:
        client = get_gemini_client()
        
        with open(image_path, "rb") as f:
            image_data = f.read()
        
        classe_predita = dados_analise.get('classe_predita', 'Desconhecida')
        classe_traduzida = dados_analise.get('classe_traduzida', 'Desconhecida')
        confianca = dados_analise.get('confianca_predita_percentual', 'N/A')
        probabilidades = dados_analise.get('probabilidades_completas', {})
        
        prompt = f"""
        You are a Clinical Decision Support Artificial Intelligence (CDSS) system specialized in the initial screening and classification of skin lesions. Your goal is to generate a concise PRELIMINARY TECHNICAL REPORT and RISK REPORT, using strictly medical language, to be read and validated by a specialist physician.
        
        INPUT INFORMATION FOR THE CLASSIFICATION MODEL (VGG16 Fine-Tuned):
        1. PREDICTED CLASS: {classe_predita} ({classe_traduzida}) - Confidence: {confianca}
        2. PROBABILITY VECTOR: {probabilidades}
        3. HISTORICAL MODEL METRICS FOR THE PREDICTED CLASS:
           - Precision: {METRICAS_MODELO.get(classe_predita, {}).get('precision', 'N/A'):.4f}
           - Recall: {METRICAS_MODELO.get(classe_predita, {}).get('recall', 'N/A'):.4f}
           - F1-Score: {METRICAS_MODELO.get(classe_predita, {}).get('f1-score', 'N/A'):.4f}

        REQUIRED INFORMATION FOR THE ANSWER (Do not exceed 300 words):

        * Identify the primary classification and the model confidence.
        * Justify. Describe the visual characteristics of the image that corroborate the classification {classe_predita} ({classe_traduzida}).
        * Perform a differential analysis. Comment on the 2-3 classes with the highest probability after the primary one, briefly explaining the similarities and differences.
        
        Format your response clearly and technically, using bullet points when appropriate, but never use titles. Only plain text and formatting such as bold, italics, lists, etc. No titles.

        Be formal and objective. NEVER USE TITLES OR SUBTITLES. NO H1, H2, H3, ETC.
        """

        from google.genai import types
        
        response = client.models.generate_content(
            model='gemini-2.5-flash-lite',
            contents=[
                prompt,
                types.Part.from_bytes(
                    data=image_data,
                    mime_type=mimetypes.guess_type(image_path)[0] or 'image/jpeg'
                )
            ]
        )
        
        return response.text.strip()
        
    except Exception as e:
        print(f"❌ Erro ao gerar descrição da imagem: {e}")
        return f"""
        **PRELIMINARY TECHNICAL REPORT - CLASSIFIED IMAGE**

        **Primary Classification:** {dados_analise.get('classe_predita', 'N/A')} ({dados_analise.get('classe_traduzida', 'N/A')})
        **Model Confidence:** {dados_analise.get('confianca_predita_percentual', 'N/A')}
        **Historical F1-Score:** {dados_analise.get('metrica_f1_classe_predita', 'N/A'):.4f}

        **Differential Analysis (Top 3):**
        {', '.join([f"{k}: {v}" for k, v in list(dados_analise.get('probabilidades_completas', {}).items())[:3]])}

        **WARNING:** This is a preliminary report generated by AI and must be validated by direct clinical evaluation.

        For pressure ulcers (Class P), the model has a historical recall of only 0.2647.
        """